genre = Category.create(:name=>"ジャンル")
area = Category.create(:name=>"地域")
musical_instrument = Category.create(:name=>"楽器")

genre_rock = genre.children.create(:name=>"ロック")
genre_jpop = genre.children.create(:name=>"Jポップ")
genre_funk = genre.children.create(:name=>"ファンク")
genre_punk = genre.children.create(:name=>"パンク")
genre_melodic_hardcore = genre.children.create(:name=>"メロコア")
genre_loud = genre.children.create(:name=>"ラウド")
genre_ska = genre.children.create(:name=>"スカ")
genre_blues = genre.children.create(:name=>"ブルース")
genre_alternative = genre.children.create(:name=>"オルタナティブ")
genre_other = genre.children.create(:name=>"その他")



area_hokaido = area.children.create(:name=>"北海道")
area_aomori = area.children.create(:name=>"青森県")
area_iwate = area.children.create(:name=>"岩手県")
area_miyagi = area.children.create(:name=>"宮城県")
area_akita = area.children.create(:name=>"秋田県")
area_ayamagata = area.children.create(:name=>"山形県")
area_hukushima = area.children.create(:name=>"福島県")
area_ibaraki = area.children.create(:name=>"茨城県")
area_totigi = area.children.create(:name=>"栃木県")
area_gunma = area.children.create(:name=>"群馬県")
area_saitama = area.children.create(:name=>"埼玉県")
area_tiba = area.children.create(:name=>"千葉県")
area_tokyo = area.children.create(:name=>"東京都")
area_kanagawa = area.children.create(:name=>"神奈川県")
area_niigata = area.children.create(:name=>"新潟県")
area_toyama = area.children.create(:name=>"富山県")
area_ishikawa = area.children.create(:name=>"石川県")
area_hukui = area.children.create(:name=>"福井県")
area_yamanashi = area.children.create(:name=>"山梨県")
area_nagano = area.children.create(:name=>"長野県")
area_gihu = area.children.create(:name=>"岐阜県")
area_shizuoka = area.children.create(:name=>"静岡県")
area_aiti = area.children.create(:name=>"愛知県")
area_mie = area.children.create(:name=>"三重県")
area_siga = area.children.create(:name=>"滋賀県")
area_kyoto = area.children.create(:name=>"京都府")
area_oosaka = area.children.create(:name=>"大阪府")
area_hyougo = area.children.create(:name=>"兵庫県")
area_nara = area.children.create(:name=>"奈良県")
area_wakayama = area.children.create(:name=>"和歌山県")
area_tottori = area.children.create(:name=>"鳥取県")
area_shimane = area.children.create(:name=>"島根県")
area_okayama = area.children.create(:name=>"岡山県")
area_hiroshima = area.children.create(:name=>"広島県")
area_yamaguti = area.children.create(:name=>"山口県")
area_tokushima = area.children.create(:name=>"徳島県")
area_kagawa = area.children.create(:name=>"香川県")
area_ehime = area.children.create(:name=>"愛媛県")
area_kouti = area.children.create(:name=>"高知県")
area_hukushima = area.children.create(:name=>"福岡県")
area_saga = area.children.create(:name=>"佐賀県")
area_nagasaki = area.children.create(:name=>"長崎県")
area_kumamoto = area.children.create(:name=>"熊本県")
area_ooita = area.children.create(:name=>"大分県")
area_miyazaki = area.children.create(:name=>"宮崎県")
area_kagoshima = area.children.create(:name=>"鹿児島県")
area_okinawa = area.children.create(:name=>"沖縄県")


musical_instrument_vocal =musical_instrument.children.create(:name=>"ボーカル")
musical_instrument_guiter =musical_instrument.children.create(:name=>"ギター")
musical_instrument_bass =musical_instrument.children.create(:name=>"ベース")
musical_instrument_doram =musical_instrument.children.create(:name=>"ドラム")
musical_instrument_keyboard =musical_instrument.children.create(:name=>"キーボード")
musical_instrument_brass =musical_instrument.children.create(:name=>"金管楽器")
musical_instrument_woodwind =musical_instrument.children.create(:name=>"木管楽器")
musical_instrument_other =musical_instrument.children.create(:name=>"その他")


